name: Build project

on:
  workflow_dispatch: {}

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: "Unity Project Settings Info"
        id: unity-project-settings-info
        uses: Breakstep-Studios/unity-project-settings-info@v1.0.0
      - name: "Output Bundle Version"
        run: |
          echo bundleVersion: ${{ steps.unity-project-settings-info.outputs.bundle-version }}
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Check Free Disk Space (Android)
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          allowDirtyBuild: true
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      - name: Zip build artifacts
        run: |
          cd $GITHUB_WORKSPACE/build/${{ matrix.targetPlatform }}
          zip -r $GITHUB_WORKSPACE/Build_${{ matrix.targetPlatform }}_${{ steps.unity-project-settings-info.outputs.bundle-version }}.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: Build_${{ matrix.targetPlatform }}_${{ steps.unity-project-settings-info.outputs.bundle-version }}
          path: Build_${{ matrix.targetPlatform }}_${{ steps.unity-project-settings-info.outputs.bundle-version }}.zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Build_${{ matrix.targetPlatform }}_${{ steps.unity-project-settings-info.outputs.bundle-version }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.unity-project-settings-info.outputs.bundle-version }}
