name: Build project

on:
  workflow_dispatch: {}

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: "Unity Project Settings Info"
        id: unity-project-settings-info
        uses: Breakstep-Studios/unity-project-settings-info@v1.0.0
      - name: "Output Bundle Version"
        run: |
          echo bundleVersion: ${{ steps.unity-project-settings-info.outputs.bundle-version }}
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Check Free Disk Space (Android)
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          allowDirtyBuild: true
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      - name: Check if Release exists
        id: check-release
        run: |
          if gh release view ${{ steps.unity-project-settings-info.outputs.bundle-version }} &> /dev/null; then
            echo "::set-output name=release_exists::true"
          else
            echo "::set-output name=release_exists::false"
          fi
        shell: bash
      - name: Create Release and Attach Build
        if: steps.check-release.outputs.release_exists != 'true'
        run: |
          # Create release
          release_id=$(gh release create "${{ steps.unity-project-settings-info.outputs.bundle-version }}" -t "${{ steps.unity-project-settings-info.outputs.bundle-version }}" -n "Release ${{ steps.unity-project-settings-info.outputs.bundle-version }}" | awk '/^ID:/{print $2}'))
      
          # Upload build files
          for file in build/${{ matrix.targetPlatform }}/*; do
            gh release upload $release_id "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
